name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and without
        run: mvn -B clean package -DskipTests

      - name: Deploy the application
        uses: appleboy/scp-action@master
        with:
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: ${{ secrets.TOMCAT_PASSWORD }}
          source: target/*.war
          target: /home/avada/web/kino.avada-media-dev1.od.ua/tomcat/webapps/*.war
            - name: Restart Tomcat
              run: ssh avada_kino@94.45.147.115 "sudo systemctl restart tomcat.service"


#      - name: Deploy to Tomcat server
#        uses: appleboy/ssh-action@master
#        with:
#          host: kino.avada-media-dev1.od.ua
#          username: ${{ secrets.TOMCAT_USERNAME }}
#          password: ${{ secrets.TOMCAT_PASSWORD }}
#          port: 22
#          script: |
#            cd /home/avada/web/kino.avada-media-dev1.od.ua/tomcat/webapps/
#            rm -rf CinemaDemo.war
#            rm -rf CinemaDemo
#            mkdir testcreating
#            cp ~/github/workspace/target/*.war CinemaDemo.war